# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmatrix.proto\x12\x06matrix\"\x1d\n\rMatrixRequest\x12\x0c\n\x04size\x18\x01 \x01(\x05\" \n\x0eMatrixResponse\x12\x0e\n\x06result\x18\x01 \x03(\x05\x32R\n\rMatrixService\x12\x41\n\x10MultiplyMatrices\x12\x15.matrix.MatrixRequest\x1a\x16.matrix.MatrixResponseB\x0bZ\t./;matrixb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matrix_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./;matrix'
  _globals['_MATRIXREQUEST']._serialized_start=24
  _globals['_MATRIXREQUEST']._serialized_end=53
  _globals['_MATRIXRESPONSE']._serialized_start=55
  _globals['_MATRIXRESPONSE']._serialized_end=87
  _globals['_MATRIXSERVICE']._serialized_start=89
  _globals['_MATRIXSERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
