// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.15.8
// source: matrix.proto

package matrix

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatrixRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int32 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"` // Size of the matrix (500x500)
}

func (x *MatrixRequest) Reset() {
	*x = MatrixRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matrix_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatrixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixRequest) ProtoMessage() {}

func (x *MatrixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_matrix_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixRequest.ProtoReflect.Descriptor instead.
func (*MatrixRequest) Descriptor() ([]byte, []int) {
	return file_matrix_proto_rawDescGZIP(), []int{0}
}

func (x *MatrixRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type MatrixResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []int32 `protobuf:"varint,1,rep,packed,name=result,proto3" json:"result,omitempty"` // Flattened matrix result after multiplication
}

func (x *MatrixResponse) Reset() {
	*x = MatrixResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_matrix_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MatrixResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixResponse) ProtoMessage() {}

func (x *MatrixResponse) ProtoReflect() protoreflect.Message {
	mi := &file_matrix_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixResponse.ProtoReflect.Descriptor instead.
func (*MatrixResponse) Descriptor() ([]byte, []int) {
	return file_matrix_proto_rawDescGZIP(), []int{1}
}

func (x *MatrixResponse) GetResult() []int32 {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_matrix_proto protoreflect.FileDescriptor

var file_matrix_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x22, 0x23, 0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x28, 0x0a, 0x0e, 0x4d,
	0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x52, 0x0a, 0x0d, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x10, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x79, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x6d, 0x61, 0x74,
	0x72, 0x69, 0x78, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x2e, 0x4d, 0x61, 0x74, 0x72, 0x69,
	0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x3b,
	0x6d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_matrix_proto_rawDescOnce sync.Once
	file_matrix_proto_rawDescData = file_matrix_proto_rawDesc
)

func file_matrix_proto_rawDescGZIP() []byte {
	file_matrix_proto_rawDescOnce.Do(func() {
		file_matrix_proto_rawDescData = protoimpl.X.CompressGZIP(file_matrix_proto_rawDescData)
	})
	return file_matrix_proto_rawDescData
}

var file_matrix_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_matrix_proto_goTypes = []interface{}{
	(*MatrixRequest)(nil),  // 0: matrix.MatrixRequest
	(*MatrixResponse)(nil), // 1: matrix.MatrixResponse
}
var file_matrix_proto_depIdxs = []int32{
	0, // 0: matrix.MatrixService.MultiplyMatrices:input_type -> matrix.MatrixRequest
	1, // 1: matrix.MatrixService.MultiplyMatrices:output_type -> matrix.MatrixResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_matrix_proto_init() }
func file_matrix_proto_init() {
	if File_matrix_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_matrix_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatrixRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_matrix_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MatrixResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_matrix_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_matrix_proto_goTypes,
		DependencyIndexes: file_matrix_proto_depIdxs,
		MessageInfos:      file_matrix_proto_msgTypes,
	}.Build()
	File_matrix_proto = out.File
	file_matrix_proto_rawDesc = nil
	file_matrix_proto_goTypes = nil
	file_matrix_proto_depIdxs = nil
}
